% this file was generated by the following command(s):
%   rebank_dist_32/bin/candc --models models --candc-super super --candc-parser model_hybrid --candc-printer boxer --candc-parser-noisy_rules=false

:- op(601, xfx, (/)).
:- op(601, xfx, (\)).
:- multifile ccg/2, id/2.
:- discontiguous ccg/2, id/2.

ccg(1,
 ba(s:dcl,
  fa(np,
   t(np/n, 'every', 'every', 'DT', 'I-NP', 'O'),
   t(n, 'man', 'man', 'NN', 'I-NP', 'O')),
  fa(s:dcl\np,
   t((s:dcl\np)/(s:ng\np), 'is', 'be', 'VBZ', 'I-VP', 'O'),
   t(s:ng\np, 'working', 'work', 'VBG', 'I-VP', 'O')))).

ccg(2,
 ba(s:dcl,
  lx(np, n,
   ba(n,
    t(n, 'everybody', 'everybody', 'DT', 'I-NP', 'O'),
    fa(n\n,
     t((n\n)/(s:dcl\np), 'who', 'who', 'WP', 'B-NP', 'O'),
     fa(s:dcl\np,
      t((s:dcl\np)/(s:ng\np), 'is', 'be', 'VBZ', 'I-VP', 'O'),
      t(s:ng\np, 'working', 'work', 'VBG', 'I-VP', 'O'))))),
  fa(s:dcl\np,
   t((s:dcl\np)/np, 'has', 'have', 'VBZ', 'B-VP', 'O'),
   fa(np,
    t(np/n, 'an', 'an', 'DT', 'I-NP', 'O'),
    fa(n,
     t(n/n, 'expensive', 'expensive', 'JJ', 'I-NP', 'O'),
     t(n, 'car', 'car', 'NN', 'I-NP', 'O')))))).

ccg(3,
 ba(s:dcl,
  fa(np,
   t(np/n, 'every', 'every', 'DT', 'I-NP', 'O'),
   t(n, 'man', 'man', 'NN', 'I-NP', 'O')),
  fa(s:dcl\np,
   t((s:dcl\np)/np, 'owns', 'own', 'VBZ', 'I-VP', 'O'),
   fa(np,
    t(np/n, 'a', 'a', 'DT', 'I-NP', 'O'),
    t(n, 'car', 'car', 'NN', 'I-NP', 'O'))))).


